### ISSUE TITLE
Error on items with condition property after update to 0.7.12

### ISSUE THREAD

**Issue by plong0** [Textalk/angular-schema-form#264]
Just updated to 0.7.12 and I am receiving this error:
```
 TypeError: undefined is not a function
    at schema-form.js:293
```

**Comment by plong0** [comment]
It is coming from a form element with a condition on it.

At first I thought it was because of a leftover "conditional" type element, so I took out the conditional and put the condition on each of its items, but I still receive the error.

**Comment by Dervisevic** [comment]
The .each method was only available with jQuery, 0.7.13 fixes the issue.

**Comment by plong0** [comment]
Thanks dudes :) 
sorry for the dupe of #263
