### ISSUE TITLE
Problem with conditional type in 0.7.12

### ISSUE THREAD

**Issue by monyiliev** [Textalk/angular-schema-form#263]
Thanks for your awesome code. I highly appreciate it.

I wanted to share an issue that I started experiencing since I upgraded to 0.7.12. In my Chrome console I am getting an error:
```
TypeError: undefined is not a function
    at schema-form.js:293
```
In my form I have the following conditional type:
```
  {
    type: "conditional",
    condition: "model.type == 1",
    items: [
      {
        key: "pseudo",
        placeholder: "Pseudo Example Placeholder"
      }
    ]
  }
```
I can confirm that the above works with 0.7.11 and AngularJS 1.3.14

I would be very grateful for your assistance with this problem.

Thanks

**Comment by Dervisevic** [comment]
The .each method was only available with jQuery, 0.7.13 fixes the issue.

**Comment by monyiliev** [comment]
Thanks so much. Upgraded to 0.7.13 and it all works. Awesome.
